### ISSUE TITLE
some author facets are not computed properly

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSimportpipeline#103]
I'll register it here, before I forget

http://localhost:8984/solr/collection1/select?q=orcid%3A%220000000326869241%22&fl=bibcode%2Cauthor&wt=json&indent=true

```
query: orcid:0000-0003-2686-9241
```

response contains facets:

```
"facet_counts": {
    "facet_queries": {},
    "facet_fields": {
      "author_facet_hier": [
        "1/Stern, D/Stern, D.",
        28,
        "1/Stern, D/Stern, Daniel",
        24,
        "1/Christensen, F/Christensen, F. E.",
        22,
```

that first result should not be there '1/Stern, D/Stern, D.' (comma shouldn't be considered bpart of the name)

**Comment by aaccomazzi** [comment]
Don't really follow this, facets look fine to me.

**Comment by romanchyla** [comment]
`"1/Christensen, F/Christensen, F. E.",` should be `"1/Christensen, F/Christensen, F E",`

fixed
