### ISSUE TITLE
Fix Protocol Error 99

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/ADSimportpipeline#113]
The log file reports:
    ProtocolError: ('Connection aborted.', error(99, 'Cannot assign requested address'))

```
ERROR    24682 [06/15/2016 22:35:41]:    2016PhyB..490...25Y: Traceback (most recent call last):
  File "/proj/adsx/ADSimportpipeline/pipeline/workers.py", line 100, in on_message
    result = json.dumps(self.strategies[producer]([content]))
```

**Comment by spacemansteve** [comment]
The code sends potentially many HTTP posts using the Python requests library.  HTTP connections are stateless and not transaction oriented.  Since they are not explicitly closed by the application or the requests library, they remain open until they are timed out by the operating system.   Per RFC 793, this timeout takes 4 minutes.  Several thousand posts each over their own socket can consume all available sockets causing a error 99 to occur.  

Potential solutions can either increase the rate sockets are closed or reduce the number of sockets opened.

**Comment by spacemansteve** [comment]
According to the documentation for the Python requests library, we can explicitly close the connect and this will recycle the socket.

**Comment by jonnybazookatone** [comment]
Can you confirm your fixes and close this ticket @spacemansteve?
