### ISSUE TITLE
Create hierarchical facets for Publication types

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#118]
Top level facets should be:
1. Article
   - Journal Article
   - Proceedings article
   - Book chapter  
   - Eprint
2. Non-Article
   - Proceedings
   - Book
   - Software 
   - ...

(this could also be done in ADSExports BTW so consider what most robust solution is)

**Comment by romanchyla** [comment]
added to solr, the ADSExports has to generate the hierarchical values for `doctype_facet_hier`

example:

```
0/Article
1/Article/Book chapter
```
