### ISSUE TITLE
Indexing last page in Solr documents

### ISSUE THREAD

**Issue by ehenneken** [adsabs/ADSimportpipeline#145]
Currently the last page and page range don't seem to get indexed. E.g.: 2012MNRAS.421.3481L ADSExports generates
```
     <page>3481</page>
     <lastpage>3487</lastpage>
     <page_range>3481-3487</page_range>
```
and I only see the start page in Solr. Related to #109?

**Comment by romanchyla** [comment]
will be done in #161
