### ISSUE TITLE
Change citation_count to be len(citations)

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#86]
Just as we compute read_count from len(readers).

**Comment by vsudilov** [comment]
If we do this, it will by default always have `citation_count:0` in the solr doc if there are no `citations`. Do we want this, or do we want to have no `citation_count` field if there is no `citation` field?

**Comment by vsudilov** [comment]
I'd lean towards not having it since it seems more tidy to me, but maybe there are concerns with how search operates?

**Comment by aaccomazzi** [comment]
I think we want to have the value set to 0 in these cases.  That's what we
have now and everything works correctly (wrt. sort, cumulative citation
counts, etc).



On Wed, Feb 25, 2015 at 10:03 AM, Vladimir Sudilovsky <
notifications@github.com> wrote:

> I'd lean towards not having it since it seems more tidy to me, but maybe
> there are concerns with how search operates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/ADSimportpipeline/issues/86#issuecomment-75975076>
> .
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA
