### ISSUE TITLE
Update handling of facets for MPECs and ApJL

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#87]
MPECs are serial publications but publication facets display a trailing letter due to their odd bibcodes.

As an example, try a search of bibstem:MPEC and see the "Publications" facet

ApJ Letter papers should have a publication facet of "ApJL" now that it is its own journal.  ADS Classic had its own hack to deal with this, but we should just deal with this in the SOLR adapter.

**Comment by vsudilov** [comment]
No problem; Which field is it? Any ideas what the logic should look like?
