### ISSUE TITLE
Index doctype in SOLR document

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#88]
This corresponds to pubtype from ADSExports

**Comment by jonnybazookatone** [comment]
Currently, 'doctype' (as per the current test stub data) is expected to have the form:
```python
'doctype': {'content': u'article', 'origin': u'ADS metadata'}
```

Would we want to retain all the information on SolrUpdating?, ie.
```python
ADS_record['metadata']['properties'].get('doctype',{})
>>> {'content': u'article', 'origin': u'ADS metadata'}
```
or only the actual doc type? ie.
```python
ADS_record['metadata']['properties'].get('doctype', {}).get('content')
>>> u'article'
```

**Comment by vsudilov** [comment]
the later; origin isn't exposed at all in Solr
