### ISSUE TITLE
certain links_data elements are wrongly escaped

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSimportpipeline#93]
pls see https://github.com/adsabs/bumblebee/issues/333

```
{"title":"HREF="http://minorplanetcenter.org/mpec/K13/K13X03.html">Available from the Minor Planet Center.</A>", "type":"priv", "instances":"", "access":""} 
```

should be
```
{"title":"HREF=\\"http://minorplanetcenter.org/mpec/K13/K13X03.html\\"">Available from the Minor Planet Center.</A>", "type":"priv", "instances":"", "access":""} 
```

**Comment by romanchyla** [comment]
actually, the title is wrong altogether; but the values should be escaped anyways

**Comment by vsudilov** [comment]
I could use a bit more context please. What data is this in Solr?

**Comment by aaccomazzi** [comment]
This was generated by bad data from ADS exports.  For the time I'm removing these links (which in classic are displayed in lieu of the abstract field).  Issue can stay open until we make a definite decision on how to deal with these cases.  My preference is to just forget about them.

**Comment by vsudilov** [comment]
Thanks alberto.

**Comment by vsudilov** [comment]
@aaccomazzi safe to close this issue now?

**Comment by aaccomazzi** [comment]
Sounds good
