### ISSUE TITLE
Too high read_count

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSimportpipeline#96]
This document seems to have a very high 'read_count' value of 4K - but metrics reports it should have only 12; what is wrong, if anything?

https://ui.adsabs.harvard.edu/#abs/2015arXiv150301104A

```
di = bbb.getController('Diagnostics')
di.getFirstDoc('bibcode:2015arXiv150301104A', {query: {q: 'bibcode:2015arXiv150301104A', fl: 'title,score,bibcode,read_count,citation,[citations]'}}).done(function(data) {d=data})
```

**Comment by ehenneken** [comment]
Nothing wrong here. The 'read_count' contains arXiv reads, while the metrics only work with ADS reads.
