### ISSUE TITLE
Multiple deletions to SOLR

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#97]
I see nightly deletions of ~6K records which is excessive given the usual match rate of eprints which is about 20/day.  Something is causing records to either not be deleted or deleted then added again.
```
adsx-401: grep 2015arXiv150403894P *.log
SolrUpdater.log:INFO	20182 [06/21/2015 08:04:22]:	Delete: 2015arXiv150403894P
SolrUpdater.log:INFO	3671 [06/22/2015 03:15:53]:	Delete: 2015arXiv150403894P
```
We probably need some debugging output to figure out what's going on upon ingest.

**Comment by vsudilov** [comment]
Is it expected that the published version references the eprint, but not the other way around?

> mnras.metadata.relations.alternates
    [
            {
                    "origin" : null,
                    "content" : "2015arXiv150403894P",
                    "type" : "eprint"
            }
    ]
    > arxiv.metadata.relations.alternates
    [ ]

**Comment by vsudilov** [comment]
Nevermind, I think it is. Sorry for the noise.

**Comment by vsudilov** [comment]
`dryrun` was set to `True` in the worker. It is not set to `False`. Do we have a strategy to verify that this is the root cause of the problem?
